version: '3.8'

services:
  nginx-log-dashboard:
    build: .
    container_name: nginx-log-dashboard
    ports:
      - "5000:5000"  # HTTPS端口
    volumes:
      # 映射nas日志目录
      - ./logs/nas:/var/log/nginx/nas:ro
      # 映射nasqb日志目录
      - ./logs/nasqb:/var/log/nginx/nasqb:ro
      # 映射SSL证书文件
      - ./certs:/app/certs:ro
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    networks:
      - nginx-dashboard-network

networks:
  nginx-dashboard-network:
    driver: bridge 